extends SceneTree

const WeaponInventory := preload("res://scripts/weapon_inventory.gd")


func _init() -> void:
	var inventory := WeaponInventory.new()
	assert(abs(inventory.current_cooldown() - (WeaponInventory.SHELL_COOLDOWN - WeaponInventory.ROUND_STARTING_COOLDOWN_ADVANCE)) < 0.01)
	assert(not inventory.is_current_ready())
	inventory.update_current_cooldown(WeaponInventory.SHELL_COOLDOWN)
	assert(inventory.is_current_ready())
	var shell_weapon: Dictionary = inventory.weapon_by_name(WeaponInventory.SHELL)
	assert(int(shell_weapon.get("damage", 0)) == WeaponInventory.SHELL_DAMAGE)
	assert(abs(float(shell_weapon.get("cooldown", 0.0)) - WeaponInventory.SHELL_COOLDOWN) < 0.01)
	assert(WeaponInventory.SHELL_DAMAGE == 40)
	assert(abs(WeaponInventory.SHELL_COOLDOWN - 4.0) < 0.01)
	assert(inventory.ammo_for(WeaponInventory.MACHINE_GUN) == 0)
	assert(inventory.stock_for(WeaponInventory.MACHINE_GUN) == 0)
	assert(not inventory.select_by_name(WeaponInventory.MACHINE_GUN))
	assert(inventory.add_ammo(WeaponInventory.MACHINE_GUN) == WeaponInventory.MACHINE_GUN_SHOP_PACK)
	assert(inventory.stock_for(WeaponInventory.MACHINE_GUN) == WeaponInventory.MACHINE_GUN_SHOP_PACK)
	assert(inventory.ammo_for(WeaponInventory.MACHINE_GUN) == 0)
	assert(not inventory.select_by_name(WeaponInventory.MACHINE_GUN))
	var machine_gun_weapon: Dictionary = inventory.weapon_by_name(WeaponInventory.MACHINE_GUN)
	assert(int(machine_gun_weapon.get("damage", 0)) == 2)
	assert(abs(float(machine_gun_weapon.get("launch_power", 0.0)) - WeaponInventory.MACHINE_GUN_CLASSIC_POWER) < 0.01)
	assert(abs(float(machine_gun_weapon.get("cooldown", 0.0)) - WeaponInventory.MACHINE_GUN_COOLDOWN) < 0.01)
	assert(int(machine_gun_weapon.get("cost", 0)) == 50)
	assert(abs(WeaponInventory.MACHINE_GUN_CLASSIC_POWER - 25.0) < 0.01)
	assert(abs(WeaponInventory.MACHINE_GUN_COOLDOWN - 0.1) < 0.01)
	inventory.reset_round_ammo()
	assert(inventory.ammo_for(WeaponInventory.MACHINE_GUN) == WeaponInventory.MACHINE_GUN_SHOP_PACK)
	assert(inventory.select_by_name(WeaponInventory.MACHINE_GUN))
	assert(inventory.consume_current_amount(1))
	assert(inventory.ammo_for(WeaponInventory.MACHINE_GUN) == WeaponInventory.MACHINE_GUN_SHOP_PACK - 1)
	assert(inventory.stock_for(WeaponInventory.MACHINE_GUN) == WeaponInventory.MACHINE_GUN_SHOP_PACK - 1)
	inventory.reset_round_ammo()
	assert(inventory.ammo_for(WeaponInventory.MACHINE_GUN) == WeaponInventory.MACHINE_GUN_SHOP_PACK - 1)

	assert(inventory.add_ammo(WeaponInventory.MIRV) == WeaponInventory.MIRV_SHOP_PACK)
	assert(inventory.ammo_for(WeaponInventory.MIRV) == 0)
	var mirv_weapon: Dictionary = inventory.weapon_by_name(WeaponInventory.MIRV)
	assert(int(mirv_weapon.get("damage", 0)) == WeaponInventory.MIRV_DAMAGE)
	assert(int(mirv_weapon.get("fragments", 0)) == WeaponInventory.MIRV_FRAGMENTS)
	assert(abs(float(mirv_weapon.get("spread", 0.0)) - WeaponInventory.MIRV_SPREAD) < 0.01)
	assert(abs(float(mirv_weapon.get("cooldown", 0.0)) - WeaponInventory.MIRV_COOLDOWN) < 0.01)
	assert(int(mirv_weapon.get("cost", 0)) == 50)
	assert(WeaponInventory.MIRV_DAMAGE == 30)
	assert(WeaponInventory.MIRV_FRAGMENTS == 5)
	assert(abs(WeaponInventory.MIRV_SPREAD - 0.2) < 0.01)
	assert(abs(WeaponInventory.MIRV_COOLDOWN - 7.5) < 0.01)
	inventory.reset_round_ammo()
	assert(inventory.select_by_name(WeaponInventory.MIRV))
	assert(inventory.ammo_for(WeaponInventory.MIRV) == WeaponInventory.MIRV_SHOP_PACK)
	assert(abs(inventory.current_cooldown() - WeaponInventory.MIRV_COOLDOWN) < 0.01)
	assert(not inventory.is_current_ready())
	inventory.update_current_cooldown(WeaponInventory.MIRV_COOLDOWN)
	assert(inventory.is_current_ready())
	assert(inventory.add_ammo(WeaponInventory.MISSILE) == WeaponInventory.MISSILE_SHOP_PACK)
	var missile_weapon: Dictionary = inventory.weapon_by_name(WeaponInventory.MISSILE)
	assert(int(missile_weapon.get("damage", 0)) == WeaponInventory.MISSILE_DAMAGE)
	assert(abs(float(missile_weapon.get("fuel", 0.0)) - 3.0) < 0.01)
	assert(abs(float(missile_weapon.get("steer_sensitivity", 0.0)) - 300.0) < 0.01)
	assert(abs(float(missile_weapon.get("powered_speed", 0.0)) - WeaponInventory.MISSILE_CLASSIC_SPEED) < 0.01)
	assert(abs(float(missile_weapon.get("cooldown", 0.0)) - WeaponInventory.MISSILE_COOLDOWN) < 0.01)
	assert(int(missile_weapon.get("cost", 0)) == 50)
	assert(WeaponInventory.MISSILE_DAMAGE == 40)
	assert(abs(WeaponInventory.MISSILE_CLASSIC_SPEED - 9.0) < 0.01)
	assert(abs(WeaponInventory.MISSILE_COOLDOWN - 5.0) < 0.01)
	assert(inventory.add_ammo(WeaponInventory.NUKE) == WeaponInventory.NUKE_SHOP_PACK)
	var nuke_weapon: Dictionary = inventory.weapon_by_name(WeaponInventory.NUKE)
	assert(int(nuke_weapon.get("damage", 0)) == WeaponInventory.NUKE_DAMAGE)
	assert(abs(float(nuke_weapon.get("cooldown", 0.0)) - WeaponInventory.NUKE_COOLDOWN) < 0.01)
	assert(int(nuke_weapon.get("cost", 0)) == 50)
	assert(bool(nuke_weapon.get("white_out", false)))
	assert(WeaponInventory.NUKE_DAMAGE == 90)
	assert(abs(WeaponInventory.NUKE_COOLDOWN - 10.0) < 0.01)

	var hidden_weapons := [
		{"name": WeaponInventory.ROLLING_MINES, "pack": WeaponInventory.ROLLING_MINES_SHOP_PACK},
		{"name": WeaponInventory.AIRSTRIKE, "pack": WeaponInventory.AIRSTRIKE_SHOP_PACK},
		{"name": WeaponInventory.DEATHS_HEAD, "pack": WeaponInventory.DEATHS_HEAD_SHOP_PACK},
		{"name": WeaponInventory.HOVER_COIL, "pack": WeaponInventory.HOVER_COIL_SHOP_PACK},
		{"name": WeaponInventory.CORBOMITE, "pack": WeaponInventory.CORBOMITE_SHOP_PACK},
	]

	for data in hidden_weapons:
		var weapon_name := str(Dictionary(data).get("name", ""))
		var pack := int(Dictionary(data).get("pack", 0))
		assert(inventory.ammo_for(weapon_name) == 0)
		assert(inventory.ammo_pack_size(weapon_name) == pack)
		assert(not inventory.select_by_name(weapon_name))
		assert(inventory.add_ammo(weapon_name) == pack)
		assert(inventory.ammo_for(weapon_name) == 0)
		inventory.reset_round_ammo()
		assert(inventory.select_by_name(weapon_name))

	assert(inventory.ammo_for(WeaponInventory.SHELL) == -1)
	assert(inventory.add_ammo(WeaponInventory.SHELL) == -1)
	quit(0)
